version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]
      
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "um44"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "um43"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]
        
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "um42"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]
